### ISSUE TITLE
Orders can't be created

### ISSUE THREAD

**Issue by anna-otrokhova** [PulseTile/PulseTile-React#75]
Here is the POST request: http://prntscr.com/hitt2o
Here is response to POST http://prntscr.com/hittdg
Here is Error in ripple-demo-out-1.log :
http://prntscr.com/hittxh
Could you help us, please?

**Comment by robtweed** [comment]
The POSTed fields for each test should be code and name, not code and text
See the post mapping definition for laborders in this file:

https://github.com/RippleOSI/Ripple-Qewd/blob/master/lib/headings/laborders.js

**Comment by anna-otrokhova** [comment]
@robtweed 

Last time when we discussed it you said that you would need to change the functionality on backend side as you didn't expect array here and it is essential for this heading.  http://prntscr.com/i2r7oo 

May I ask please if you have already implemented the needed changes for this or something changed?

**Comment by robtweed** [comment]
On looking at the back-end code it looks like it should work and will cater for your array.  Try changing the property names for each object in the array to "code" and "name" and see if it works

**Comment by anna-otrokhova** [comment]
Ok. We will try on Monday. Thank you.

**Comment by anna-otrokhova** [comment]
@robtweed We have tested it as you proposed https://prnt.sc/i31bck . Unfortunately, it doesn't work anyway. 
Meanwhile, we have several questions:
1) What fields do you expect to be sent,  which ones are mandatory?
2) Do we send the right fields (you can see it on the screen above)?
3) Shall we send the field with  DateCreated?

**Comment by robtweed** [comment]
You're not sending the orders as an array.  You're sending as an object/hash with properties '0', '1' etc:

{
        "0": {
            "code": "order1",
            "name": "Xray Chest X-ray"
        },
        "1": {
            "code": "order2",
            "name": "Radiology-CT Head"
        },

Try again using an array as the request payload and let me know what happens

Rob

**Comment by anna-otrokhova** [comment]
@robtweed 
Ok. We will check

**Comment by anna-otrokhova** [comment]
@robtweed 
We have tested using an array as the request payload and here is our request prntscr.com/i4aphw , we get "laborders saved", but no results.

Could you please check what is wrong?

**Comment by robtweed** [comment]
OK - try it again - I think it should work now.  

However, please fix the request payload you're sending which is currently this:

[{
    "code": "order1",
    "name": "Xray Chest X-ray"
}, {
    "code": "order2",
    "name": "Radiology-CT Head"
}, "9999999000"]

Please get rid of that NHS number element.  The request body should be:

[{
    "code": "order1",
    "name": "Xray Chest X-ray"
}, {
    "code": "order2",
    "name": "Radiology-CT Head"
}]

Rob

**Comment by anna-otrokhova** [comment]
@robtweed 
It doesn't work anyway. 
And it's essential for us to send NHS number in request payload as we create URL by taking this information from request payload. To change this logic means arranging additional works that are out of scope.

**Comment by robtweed** [comment]
It appears to be a Flat JSON issue - awaiting feedback from Ian.

The normal heading payload would not normally include the NHS Number within an array - laborders is the only heading that expects an array as the payload.  Looking at the logs, it appears that you no longer send it in the request now anyway, so it looks like it's been fixed anyway

**Comment by anna-otrokhova** [comment]
ok. Let us know when we can check again, please. Thank you

**Comment by freshehr** [comment]
@robtweed @anna-otrokhova This should be working now - wrong template was loaded into EtherCis.

**Comment by anna-otrokhova** [comment]
@freshehr 
Unfortunately, I still can't create orders though I get no errors when I send POST request. 

I have a question. @robtweed , could you help me, previously you said that backend expects the body: 
[{
"code": "order1",
"name": "Xray Chest X-ray"
}, {
"code": "order2",
"name": "Radiology-CT Head"
}]

1) But there are other fields that we usually send there because we have columns for them such as:
"author":"bob.smith@gmail.com","dateCreated":"1519035350000","source":"ethercis"
Where could we add these fields? Should we send "source":"ethercis" or will we get this field from the backed side when do GET?

If we send like this:
[{
"code": "order1",
"name": "Xray Chest X-ray"
}, {
"code": "order2",
"name": "Radiology-CT Head"
},
"userId":"9999999000", "author":"bob.smith@gmail.com","dateCreated":"1519035350000"]

2) We usually get such kind of fields from back end side by GET detail request:
Request URL:http://dev.ripple.foundation/api/patients/9999999000/laborders/e62d5d5f-2daf-48f0-8d5d-573e10ff4753
{name: "Cardiac-ECG", code: "order3", terminology: "SNOMED-CT", orderDate: 1459845495014,…}
author:"Dr John Smith"
code:"order3"
dateCreated:1459845501000
name:"Cardiac-ECG"
orderDate:1459845495014
source:"ethercis"
sourceId:"e62d5d5f-2daf-48f0-8d5d-573e10ff4753"
terminology:"SNOMED-CT"

3) It is not very clear how it should be displayed the name of orders when we create orders by choosing several available orders http://prntscr.com/igs9gg .
Should be the name created like all of these orders separated by"," for example: name: "Xray Chest X-ray, Radiology-CT Head, Cardiac-ECG, Physio-crutches"?

4) Also, why are there several fields related to dates in GET response? :
 date Created:1459845501000
orderDate:1459845495014

Do you expect user to choose the date of order and date of creation?

@robtweed Could you please assist with these questions.

**Comment by robtweed** [comment]
The QEWD back-end takes the array of code/name pairs and generates a POST request for each one.  The problem is we're getting an error from EtherCIS - it's still complaining about the timing field.  Here's an example - the FlatJSON being sent to EtherCIS:

{
  "host": "ethercis",
  "url": "/rest/v1/composition",
  "queryString": {
    "templateId": "IDCR - Laboratory Order.v0",
    "ehrId": "cd8abecd-9925-4313-86af-93aab4930eae",
    "format": "FLAT"
  },
  "method": "POST",
  "session": "sessionId:127.0.0.1-guest-1519903199259-860530242-33",
  "options": {
    "body": {
      "ctx/composer_name": "Dr Tony Shannon",
      "ctx/health_care_facility|id": "999999-345",
      "ctx/health_care_facility|name": "Northumbria Community NHS",
      "ctx/id_namespace": "NHS-UK",
      "ctx/id_scheme": "2.16.840.1.113883.2.1.4.3",
      "ctx/language": "en",
      "ctx/territory": "GB",
      "ctx/time": "2018-03-01T11:21:14Z",
      "laboratory_order/laboratory_test_request/request/service_requested|code": "",
      "laboratory_order/laboratory_test_request/request/service_requested|value": "",
      "laboratory_order/laboratory_test_request/request/service_requested|terminology": "SNOMED-CT",
      "laboratory_order/laboratory_test_request/request/timing": "R5/2015-08-12T22:00:00+02:00/P2M",
      "laboratory_order/laboratory_test_request/request/timing|formalism": "timing",
      "laboratory_order/laboratory_test_request/narrative": "",
      "laboratory_order/laboratory_test_tracker/ism_transition/current_state|code": "526",
      "laboratory_order/laboratory_test_tracker/ism_transition/current_state|value": "planned",
      "laboratory_order/laboratory_test_tracker/ism_transition/current_state|terminology": "openehr",
      "laboratory_order/laboratory_test_tracker/ism_transition/careflow_step|code": "at0003",
      "laboratory_order/laboratory_test_tracker/ism_transition/careflow_step|value": "Test Requested",
      "laboratory_order/laboratory_test_tracker/ism_transition/careflow_step|terminology": "local",
      "laboratory_order/laboratory_test_tracker/test_name|code": "",
      "laboratory_order/laboratory_test_tracker/test_name|value": "",
      "laboratory_order/laboratory_test_tracker/test_name|terminology": "SNOMED-CT"
    }
  }
}

and the error response:

<html>\n<head>\n<meta http-equiv=\"Content-Type\" content=\"text/html;charset=ISO-8859-1\"/>\n<title>Error 500 </title>\n</head>\n<body>\n<h2>HTTP ERROR: 500</h2>\n<p>Problem accessing /rest/v1/composition. Reason:\n<pre>    #1.0.0 Invocation exception to method:create:java.lang.IllegalArgumentException: Could not convert JSON map:com.marand.thinkehr.f.b.b.a: Unknown segment: request! (path: laboratory_order/laboratory_test_request/request/timing)</pre></p>\n<hr /><a href=\"http://eclipse.org/jetty\">Powered by Jetty:// 9.3.z-SNAPSHOT</a><hr/>\n</body>\n</html>\n

Any ideas, Ian?

**Comment by robtweed** [comment]
Anne: Regarding your question concerning the request format when posting more than one order

"But there are other fields that we usually send there because we have columns for them such as:
"author":"bob.smith@gmail.com","dateCreated":"1519035350000","source":"ethercis"
Where could we add these fields? Should we send "source":"ethercis" or will we get this field from the backed side when do GET?"

Author is optional - Dr Tony Shannon is the default.  If you want to specify the author, add it to each object in the array, eg

[{
"code": "order1",
"name": "Xray Chest X-ray",
 "author": "Dr Smith"
}, {
"code": "order2",
"name": "Radiology-CT Head",
 "author": "Dr Smith"
}]

Date Created is not needed - QEWD sets this as the current date/time automatically for each POST request it sends to EtherCIS

Source is not needed either - EtherCIS is assumed to be the target to which the new Order record(s) is/are POSTed

**Comment by anna-otrokhova** [comment]
@robtweed 

Rob, Thank you for the information. According to the project we would need Date and Source as we have the appropriate columns to be displayed. https://prnt.sc/ilc41r

I suppose we could send POST request without Date and source, but anyway we should get these fields in response to Get request. Is it possible?

Also, I should mention that we have to send this field for our purposes, please ignore it.  "userId":"9999999000"

**Comment by robtweed** [comment]
Anne - regarding your question:

"It is not very clear how it should be displayed the name of orders when we create orders by choosing several available orders http://prntscr.com/igs9gg .
Should be the name created like all of these orders separated by"," for example: name: "Xray Chest X-ray, Radiology-CT Head, Cardiac-ECG, Physio-crutches"?"

As Ian has explained, each individual code/value pair that is sent when you create a set of orders is saved individually with its own unique sourceId in EtherCIS.  There is nothing in the OpenEHR Template that links them together, except, I suppose the creation date/time.

Perhaps,. Ian, you could add an extra field to the template - eg order_name  which could be applied to each of the code/value pairs.  eg PulseTile could then send:

[{
"order_name": "Order 1",
"code": "order1",
"name": "Xray Chest X-ray",
"author": "Dr Smith"
}, {
"order_name": "Order 1",
"code": "order2",
"name": "Radiology-CT Head",
"author": "Dr Smith"
}]

If that field was then retrieved by the GET (via an AQL request to OpenEHR), then PulseTile would have a field that would allow grouping of the individual records in the resultSet

**Comment by robtweed** [comment]
Anne - you'll get the fields Author, Source and DateCreated back when you GET the orders.  But QEWD will ignore the Source and DateCreated fields if you send them from PulseTile because it doesn't need them from PulseTile in order to POST new records to EtherCIS

**Comment by anna-otrokhova** [comment]
Ok. Thank you. @robtweed @freshehr Could you please inform when your changes are ready to let us test it from our side? Thank you in advance.

**Comment by freshehr** [comment]
As I said above, the current template is only designed to handle a single order and to work only for lab orders. Making the change to the template is fairly trivial but we do need to distinguish each order. My suggestion is that we just create a uid for each order, so that they can be distinguished in the UI, and so that they can be tracked.

I will not be able to make those changes until next week I'm afraid.

Ian

**Comment by robtweed** [comment]
Yes I think that having such an extra UID field would work.  QEWD could assign its value when it packages up the set of requests for each of the orders and sends them to the OpenEHR machine.  QEWD could also probably group them together again when it retrieves the individual order records, using that UID as the group identifier.  That should keep the work on the OpenEHR template side to a minimum. and also minimise the work in PulseTile

**Comment by robtweed** [comment]
Ian - if you could also check to see why the timing field is causing problems when posting to EtherCIS - when you have the availability.  Thanks!

**Comment by freshehr** [comment]
It will also help with FHIR alignment. We shouldnlt need the groupingID - the compositionId will do that.

I've no idea why timing is now causing an issue. It used to work fine.

Ian

**Comment by freshehr** [comment]
@robtweed - there are a few mandatory elements unpopulated in the example above.
```
"laboratory_order/laboratory_test_request/request/service_requested|code": "",
"laboratory_order/laboratory_test_request/request/service_requested|value": "",
```
You have to populate the name and code of the test requested (assuming that this a coded value)

If it is just a text-only value for the request name, you just send
"laboratory_order/laboratory_test_request/request/service_requested": "Urea and Electrolytes",
no need to send the |code and |terminology lines. This is only needed for coded_text.

Timing is fine but narrative need to be populated - in this case just use the test reuest name
`"laboratory_order/laboratory_test_request/narrative": "Urea and Electrolytes",`

Same thing applies to these lines as above - this is the Action archetype which tracks the status of the order, and the test name should match that in the order.

for a coded_text

```
"laboratory_order/laboratory_test_tracker/test_name|code": "12345",
"laboratory_order/laboratory_test_tracker/test_name|value": "Urea and Electrolytes",
"laboratory_order/laboratory_test_tracker/test_name|terminology": "SNOMED-CT"
```
or for a simple uncoded text...
```
"laboratory_order/laboratory_test_tracker/test_name": "Urea and Electrolytes",
```

**Comment by robtweed** [comment]
Hi Ian - actually I posted an erroneous record, the reason for which I know and I'll get rid of.  However the POSTed requests seem to go through OK - here's the pair I just tried - first the request bodies:

    "body": {
      "ctx/composer_name": "Dr Tony Shannon",
      "ctx/health_care_facility|id": "999999-345",
      "ctx/health_care_facility|name": "Northumbria Community NHS",
      "ctx/id_namespace": "NHS-UK",
      "ctx/id_scheme": "2.16.840.1.113883.2.1.4.3",
      "ctx/language": "en",
      "ctx/territory": "GB",
      "ctx/time": "2018-03-01T17:46:16Z",
      "laboratory_order/laboratory_test_request/request/service_requested|code": "order1",
      "laboratory_order/laboratory_test_request/request/service_requested|value": "Xray Chest X-ray",
      "laboratory_order/laboratory_test_request/request/service_requested|terminology": "SNOMED-CT",
      "laboratory_order/laboratory_test_request/request/timing": "R5/2015-08-12T22:00:00+02:00/P2M",
      "laboratory_order/laboratory_test_request/request/timing|formalism": "timing",
      "laboratory_order/laboratory_test_request/narrative": "Xray Chest X-ray",
      "laboratory_order/laboratory_test_tracker/ism_transition/current_state|code": "526",
      "laboratory_order/laboratory_test_tracker/ism_transition/current_state|value": "planned",
      "laboratory_order/laboratory_test_tracker/ism_transition/current_state|terminology": "openehr",
      "laboratory_order/laboratory_test_tracker/ism_transition/careflow_step|code": "at0003",
      "laboratory_order/laboratory_test_tracker/ism_transition/careflow_step|value": "Test Requested",
      "laboratory_order/laboratory_test_tracker/ism_transition/careflow_step|terminology": "local",
      "laboratory_order/laboratory_test_tracker/test_name|code": "order1",
      "laboratory_order/laboratory_test_tracker/test_name|value": "Xray Chest X-ray",
      "laboratory_order/laboratory_test_tracker/test_name|terminology": "SNOMED-CT"
    }

    "body": {
      "ctx/composer_name": "Dr Tony Shannon",
      "ctx/health_care_facility|id": "999999-345",
      "ctx/health_care_facility|name": "Northumbria Community NHS",
      "ctx/id_namespace": "NHS-UK",
      "ctx/id_scheme": "2.16.840.1.113883.2.1.4.3",
      "ctx/language": "en",
      "ctx/territory": "GB",
      "ctx/time": "2018-03-01T17:46:16Z",
      "laboratory_order/laboratory_test_request/request/service_requested|code": "order2",
      "laboratory_order/laboratory_test_request/request/service_requested|value": "Radiology-CT Head",
      "laboratory_order/laboratory_test_request/request/service_requested|terminology": "SNOMED-CT",
      "laboratory_order/laboratory_test_request/request/timing": "R5/2015-08-12T22:00:00+02:00/P2M",
      "laboratory_order/laboratory_test_request/request/timing|formalism": "timing",
      "laboratory_order/laboratory_test_request/narrative": "Radiology-CT Head",
      "laboratory_order/laboratory_test_tracker/ism_transition/current_state|code": "526",
      "laboratory_order/laboratory_test_tracker/ism_transition/current_state|value": "planned",
      "laboratory_order/laboratory_test_tracker/ism_transition/current_state|terminology": "openehr",
      "laboratory_order/laboratory_test_tracker/ism_transition/careflow_step|code": "at0003",
      "laboratory_order/laboratory_test_tracker/ism_transition/careflow_step|value": "Test Requested",
      "laboratory_order/laboratory_test_tracker/ism_transition/careflow_step|terminology": "local",
      "laboratory_order/laboratory_test_tracker/test_name|code": "order2",
      "laboratory_order/laboratory_test_tracker/test_name|value": "Radiology-CT Head",
      "laboratory_order/laboratory_test_tracker/test_name|terminology": "SNOMED-CT"
    }

And EtherCIS appears to save them:

response from ethercis: {"compositionUid":"1d6140c2-aef5-4642-bd08-e995f4b6d946::vm01.ethercis.org::1","meta":{"href":"rest/v1/composition?uid=1d6140c2-aef5-4642-bd08-e995f4b6d946::vm01.ethercis.org::1"},"action":"CREATE"}
** cached session for ethercis not shut down

response from ethercis: {"compositionUid":"46f782da-b0af-4d48-8f0e-5713ac83d938::vm01.ethercis.org::1","meta":{"href":"rest/v1/composition?uid=46f782da-b0af-4d48-8f0e-5713ac83d938::vm01.ethercis.org::1"},"action":"CREATE"}

Do these two POSTings look OK?

However, retrieving these records doesn't go so well:

{"Test_name":null,"uid":"1d6140c2-aef5-4642-bd08-e995f4b6d946::vm01.ethercis.org::1","code":null,"terminology":null,"author":"Dr Tony Shannon","date_created":"2018-03-01T17:46:16Z","name":null,"date_ordered":null}

,{"Test_name":null,"uid":"46f782da-b0af-4d48-8f0e-5713ac83d938::vm01.ethercis.org::1","code":null,"terminology":null,"author":"Dr Tony Shannon","date_created":"2018-03-01T17:46:16Z","name":null,"date_ordered":null}

The AQL used was:

{"aql":" select     a/uid/value as uid,     a/composer/name as author,     a/context/start_time/value as date_created,     a_a/activities[at0001]/description[at0009]/items[at0121]/value/value as name,     a_a/activities[at0001]/description[at0009]/items[at0121]/value/defining_code/code_string as code,     a_a/activities[at0001]/description[at0009]/items[at0121]/value/defining_code/terminology_id/value as terminology,     b_a/description[at0001]/items[at0017]/value/value as Test_name,     b_a/time/value as date_ordered from EHR e[ehr_id/value='cd8abecd-9925-4313-86af-93aab4930eae'] contains COMPOSITION a contains (     INSTRUCTION a_a[openEHR-EHR-INSTRUCTION.request-lab_test.v1] or     ACTION b_a[openEHR-EHR-ACTION.laboratory_test.v1]) where a/name/value='Laboratory order' "}

I guess something is out of kilter, perhaps the AQL?  

Rob

**Comment by freshehr** [comment]
@robtweed : Indeed a mnor typo in AQL but significant
Try this ..
```
select a/uid/value as uid, a/composer/name as author, a/context/start_time/value as date_created, a_a/activities[at0001]/description[at0009]/items[at0121]/value/value as name, a_a/activities[at0001]/description[at0009]/items[at0121]/value/defining_code/code_string as code, a_a/activities[at0001]/description[at0009]/items[at0121]/value/defining_code/terminology_id/value as terminology, b_a/description[at0001]/items[at0017]/value/value as Test_name, b_a/time/value as date_ordered from EHR e[ehr_id/value='cd8abecd-9925-4313-86af-93aab4930eae'] contains COMPOSITION a contains ( INSTRUCTION a_a[openEHR-EHR-INSTRUCTION.request-lab_test.v1] or ACTION b_a[openEHR-EHR-ACTION.laboratory_test.v0]) where a/name/value='Laboratory order' 
```

**Comment by robtweed** [comment]
Ian

I switched the laborders.aql file to your new version (from what I could see the only change was:

  ACTION b_a[openEHR-EHR-ACTION.laboratory_test.v1])

to

  ACTION b_a[openEHR-EHR-ACTION.laboratory_test.v0])

ie the version number.  However, it still just retrieves null values from EtherCIS for me:

{"Test_name":null,"uid":"a0a301a4-02b6-4f97-bd57-47a17f45c3ec::vm01.ethercis.org::1","code":null,"terminology":null,"author":"Dr Tony Shannon","date_created":"2018-03-02T09:00:24Z","name":null,"date_ordered":null}

**Comment by robtweed** [comment]
Also Ian - would it be possible to clear out all the lab orders for 9999999000 (Ivor Cox) on EtherCIS? - it will be a lot easier to find new test postings and there's probably a lot of broken data in there

**Comment by robtweed** [comment]
Anne - Just checking what is sent by PulseTile when you create lab orders.  It appears to ignore the items I selected from the menu (XRay Chest X-Ray and Physio Crutches) and sent a POST request for XRay Chest X-ray and Radiology-CT Head.   Was I doing something wrong or is there a problem in PulseTile?

**Comment by kbeloborodko** [comment]
Hi, @robtweed, thank you very much for your response. First of all, I would like to answer your query:
Anne - Just checking what is sent by PulseTile when you create lab orders. It appears to ignore the items I selected from the menu (XRay Chest X-Ray and Physio Crutches) and sent a POST request for XRay Chest X-ray and Radiology-CT Head. Was I doing something wrong or is there a problem in PulseTile?

_Most likely, you were following the right pattern, but we were having predefined test data in the frontend code until the order issues have been resolved, so you were seeing same records creation each time_

**Comment by kbeloborodko** [comment]
Hi, @robtweed, today we were testing the Orders Heading with the real data. The good news is that records are now being created and we can fetch them, the bad news is that for some reason they are created with empty data inside of them.

**Steps to reproduce:**
1) Login as IDCR user and go to one of the patient's Orders heading page https://securedev.ripple.foundation/index.html#/patients/9999999061/orders
2) Choose Xray Chest X-ray
3) Click Create button
4) PulseTile is sending the following payload:
```
[
  {
    code: "order1",
    name: "Xray Chest X-ray"
  }
]
```
5) QEWD responds with records that contain an empty name and orderDate fields
```
[
  {
    name: "",
    orderDate: "",
    source: "ethercis",
    sourceId: "12ca6042-a13b-4665-9f37-9e0e026f6235"
  }
]
```
**Actual Result**
QEWD responds with records that have empty name and orderDate fields
**Expected Result**
QEWD responds with records that have name and orderDate fields filled with data

CC: @tony-shannon

**Comment by robtweed** [comment]
Kyrill - yes - see my earlier note about EtherCIS returning null data - you're seeing the same issue.  Ian needs to investigate I think

**Comment by tony-shannon** [comment]
will need retesting to see if current issue
